<script src="{{asset('/js/app.js')}}"></script>
<!-- JS Scripts -->
<script src="/frontend/js/jquery-3.2.1.js"></script>
<script src="/frontend/js/jquery.appear.js"></script>
<script src="/frontend/js/jquery.mousewheel.js"></script>
<script src="/frontend/js/perfect-scrollbar.js"></script>
<script src="/frontend/js/jquery.matchHeight.js"></script>
<script src="/frontend/js/svgxuse.js"></script>
<script src="/frontend/js/imagesloaded.pkgd.js"></script>
<script src="/frontend/js/Headroom.js"></script>
<script src="/frontend/js/velocity.js"></script>
<script src="/frontend/js/ScrollMagic.js"></script>
<script src="/frontend/js/jquery.waypoints.js"></script>
<script src="/frontend/js/jquery.countTo.js"></script>
<script src="/frontend/js/popper.min.js"></script>
<script src="/frontend/js/material.min.js"></script>
<script src="/frontend/js/bootstrap-select.js"></script>
<script src="/frontend/js/smooth-scroll.js"></script>
<script src="/frontend/js/selectize.js"></script>
<script src="/frontend/js/swiper.jquery.js"></script>
<script src="/frontend/js/moment.js"></script>
<script src="/frontend/js/daterangepicker.js"></script>
<script src="/frontend/js/simplecalendar.js"></script>
<script src="/frontend/js/fullcalendar.js"></script>
<script src="/frontend/js/isotope.pkgd.js"></script>
<script src="/frontend/js/ajax-pagination.js"></script>
<script src="/frontend/js/Chart.js"></script>
<script src="/frontend/js/chartjs-plugin-deferred.js"></script>
<script src="/frontend/js/circle-progress.js"></script>
<script src="/frontend/js/loader.js"></script>
<script src="/frontend/js/run-chart.js"></script>
<script src="/frontend/js/jquery.magnific-popup.js"></script>
<script src="/frontend/js/jquery.gifplayer.js"></script>
<script src="/frontend/js/mediaelement-and-player.js"></script>
<script src="/frontend/js/mediaelement-playlist-plugin.min.js"></script>

<script src="/frontend/js/base-init.js"></script>
<script defer src="/frontend/fonts/fontawesome-all.js"></script>

<script src="/frontend/Bootstrap/dist/js/bootstrap.bundle.js"></script>